### PR TITLE
fix(firewall): remove decoding bundle for expired message

### LINKED ISSUE #1649: Remove decoding bundle for expired message
We decode the bundle to detect the consensus height for nodes running on version 1.6.3 and lower. This helps maintain backward compatibility until the majority of the network upgrades. We can remove the bundle decoding in version 1.8.0 to simplify the code logic.

### PR DESCRIPTION
**Pull request by ja7ad**
## Description

Remove decoding bundle for expired message

## Related issue(s)

- Fixes #1649

### CODE REVIEW

**Review by b00f — APPROVED** [review]

File: sync/firewall/firewall.go [hunk 1]
```diff
@@ -217,35 +217,20 @@ func (f *Firewall) isExpiredMessage(msgData []byte) bool {
...
 
-	// TODO: we remove on the version v1.8.0
-	consensusHeightExtracted := false
-	var consensusHeight uint32
+	// Validate the format before extracting consensusHeight
 	consensusHeightBytes := msgData[msgLen-6:]
-	// Check if consensus height is set. Refer to the bundle encoding for more details.
-	if consensusHeightBytes[0] == 0x04 && consensusHeightBytes[1] == 0x1a {
-		consensusHeight = binary.BigEndian.Uint32(consensusHeightBytes[2:])
+	if consensusHeightBytes[0] != 0x04 || consensusHeightBytes[1] != 0x1a {
```
Comment (b00f) [inline sync/firewall/firewall.go:222]: This line can be removed.

**Review by b00f — APPROVED** [review]

**Review by b00f — APPROVED** [review]

**Review by b00f — CHANGES_REQUESTED** [review]
@Ja7ad 

If the reported consensus height in a message (here)  is not same as the actual consensus height of a message, sender should be banned.

**Comment by Ja7ad** [comment]
> @Ja7ad
> 
> If the reported consensus height in a message (here) is not same as the actual consensus height of a message, sender should be banned.

What your suggestion for fix this issue?

**Review by b00f — APPROVED** [review]
