### PR TITLE
fix(executor): not rejecting bond transaction for bootstrap validator

### LINKED ISSUE #900: Unable to sync the blockchain
## Description

Unable to sync the blockchain in Testnet at block 35861. Restarting the node won't fix the issue.

```
WRN committing block failed, removing block from the cache error="invalid public key: public key is not set" _sync="{☍ 30 ⛃ 240}" height=35861
```

### What Happened

Fixing #869 has backfired. Block 35861 contains a Bond transaction for a bootstrap validator. The bootstrap validator has a public key, but at the same time, the `LastBondingHeight` for the bootstrap validator has been set to zero.

We can fix this by adding a new method to the Sandbox to determine if the Validator is sandboxed or not. However, this will add more complexity to the code. The issue #869 is rare and occurs only once in Testnet. This issue is not permanent; for example, after one day (once the first transaction expires), it will be fixed, or users can broadcast the transaction to other nodes. Fixing both issues will increase the code complexity and make the code harder to understand.

It's better to revert the fix for #869.

### PR DESCRIPTION
**Pull request by b00f**
## Description

This PR reverts PR #870  and fixes issue #900.

## Related issue(s)

- Fixes #900 (Related to #869 )

### CODE REVIEW

File: sandbox/mock.go [hunk 1]
```diff
@@ -89,9 +81,6 @@ func (m *MockSandbox) AnyRecentTransaction(txID tx.ID) bool {
 
 func (m *MockSandbox) Validator(addr crypto.Address) *validator.Validator {
 	val, _ := m.TestStore.Validator(addr)
-	if val == nil {
-		return m.TestSandboxVals[addr]
-	}
 	return val
```
Comment (kehiy) [inline sandbox/mock.go:84]: what if the validator was nil here? are we check that in the upper layers?

Comment (b00f) [reply sandbox/mock.go:84]: It can be `nil`. In that case, the new validator should be created using `MakeNewValidator`. Please note that this is a mock and is used only for testing purposes.

Comment (kehiy) [reply sandbox/mock.go:84]: Ok, got it.

**Review by kehiy — APPROVED** [review]
everything looks good.
