### PR TITLE
fix(util): chunked download to improve download speed

### LINKED ISSUE #1453: Downloader should be able to download files in chunks
## Describe the problem you'd like to have solved

The current [Downloader](https://github.com/pactus-project/pactus/tree/main/util/downloader) package downloads the file as a whole. This might cause the downloader to be slow in action.

### Describe the ideal solution

We should be able to download a file in chunks. It is also important to see if we can calculate each chunk's hash and re-download them if there is any mismatch in the hash or a failure.

### Additional context

This should be very carefully tested with random tests using local files of random sizes and random content.

### PR DESCRIPTION
**Pull request by Ja7ad**
## Description

Improved download speed with chunk download.

## Related issue(s)

- Fixes #1453

### CODE REVIEW

**Review by maxipaz — APPROVED** [review]
LGTM! Just left some minor comments

File: util/downloader/chunk.go [hunk 1]
```diff
@@ -0,0 +1,27 @@
+package downloader
+
+import "fmt"
+
+type chunk struct {
+	start, end int64
+}
+
+func createChunks(contentLength, totalChunks int64) []*chunk {
```
[the remark this answers is not in the document]
Comment (Ja7ad) [reply util/downloader/chunk.go:9]: `contentLength` type int64 better we work with int64.

File: util/downloader/chunk.go [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+	var chunks []*chunk
+	chunkSize := contentLength / totalChunks
```
[the remark this answers is not in the document]
Comment (Ja7ad) [reply util/downloader/chunk.go:11]: `totalChunks` is number of chunk for simulate concurrent download, default is 16.

File: util/downloader/downloader.go [hunk 3]
```diff
@@ -182,83 +182,68 @@ func (d *Downloader) downloadFile(ctx context.Context, out *os.File, stats *Stat
...
 	}
 
-	return req, nil
-}
+	buf := make([]byte, 32*1024) // 32KB buffer for reading the response body
+	offset := c.start
+	for {
+		n, err := resp.Body.Read(buf)
+		if n > 0 {
+			d.mu.Lock()
```
[the remark this answers is not in the document]
Comment (Ja7ad) [reply util/downloader/downloader.go:194]: We can't use defer in for loop, possible resource leak, 'defer' is called in the 'for' loop

File: util/downloader/chunk_test.go [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+)
+
+func TestCreateChunks(t *testing.T) {
+	tests := []struct {
+		contentLength int64
+		totalChunks   int64
+		expected      []*chunk
+	}{
+		{
+			contentLength: 181403648,
```
Comment (b00f) [inline util/downloader/chunk_test.go:16]: These values should be random. We can address this in another PR.

File: util/downloader/err.go [hunk 5]
```diff
@@ -0,0 +1,13 @@
+package downloader
```
Comment (b00f) [inline util/downloader/err.go:1]: 1- Please rename the file to `errors.go` to maintain consistency with the rest of the project.
2- These errors don't carry useful information since they lack a reason for the error.

File: util/downloader/chunk.go [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+		if i == totalChunks-1 {
+			end = contentLength - 1
+		}
+		chunks = append(chunks, &chunk{start: start, end: end})
+	}
+
+	return chunks
+}
+
+func (c *chunk) rangeHeader() string { return fmt.Sprintf("bytes=%d-%d", c.start, c.end) }
```
Comment (b00f) [inline util/downloader/chunk.go:25]: Nope, expand the curved brackets. Why don't we have linter for that?

File: util/downloader/chunk.go [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+
+func (c *chunk) size() int64 { return (c.end + 1) - c.start }
```
Comment (b00f) [inline util/downloader/chunk.go:27]: Same here

File: util/downloader/chunk_test.go [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+			contentLength: 0,
+			totalChunks:   1,
+			expected: []*chunk{
+				{start: 0, end: -1},
+			},
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run("", func(t *testing.T) {
```
Comment (b00f) [inline util/downloader/chunk_test.go:63]: Technically you can remove this line, when you don't have name for the test.

File: util/downloader/chunk_test.go [hunk 9]
```diff
@@ -0,0 +1,118 @@
...
+			expected: "bytes=0-499",
+		},
+		{
+			chunk:    chunk{start: 500, end: 999},
+			expected: "bytes=500-999",
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run("", func(t *testing.T) {
```
Comment (b00f) [inline util/downloader/chunk_test.go:86]: Same here, better add a name for the tests.

File: util/downloader/chunk_test.go [hunk 10]
```diff
@@ -0,0 +1,118 @@
...
+			expected: 500,
+		},
+		{
+			chunk:    chunk{start: 0, end: 0},
+			expected: 1,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run("", func(t *testing.T) {
```
Comment (b00f) [inline util/downloader/chunk_test.go:113]: Again here.

File: util/downloader/downloader.go [hunk 11]
```diff
@@ -6,24 +6,16 @@ import (
...
-	ErrCreateDir          = errors.New("create dir error")
-	ErrInvalidFilePath    = errors.New("file path is a directory, not a file")
-	ErrGetFileInfo        = errors.New("get file info error")
-	ErrCopyExistsFileData = errors.New("error copying existing file data")
-	ErrDoRequest          = errors.New("error doing request")
-	ErrFileWriting        = errors.New("error writing file")
-	ErrNewRequest         = errors.New("error creating request")
-	ErrOpenFileExists     = errors.New("error opening existing file")
+const (
+	_defaultConcurrencyPerChunk = 16
```
Comment (b00f) [inline util/downloader/downloader.go:17]: Why do you put an underscore (`_`) at the beginning of the private variable?

File: util/downloader/downloader.go [hunk 12]
```diff
@@ -35,6 +27,11 @@ type Downloader struct {
 	fileName  string
 	statsCh   chan Stats
 	errCh     chan error
+
+	chunks []*chunk
+
+	mu         sync.Mutex
```
Comment (b00f) [inline util/downloader/downloader.go:33]: To be consistent with the rest of the project, define it like:

```
type Downloader struct {
       lk sync.Mutex // lk (not mu)
        
        fileName  string   // filename (not fileName)
	statsCh   chan Stats
	errCh     chan error
	chunks []*chunk
}
```

File: util/downloader/downloader.go [hunk 13]
```diff
@@ -106,13 +104,25 @@ func (d *Downloader) download(ctx context.Context) {
...
+			if err != nil {
+				d.handleError(err)
+
+				return
+			}
+		}(c)
 	}
 
-	if err := d.downloadFile(ctx, out, &stats); err != nil {
+	wg.Wait()
```
Comment (b00f) [inline util/downloader/downloader.go:123]: If one chunk got an error, do we have wait here?

File: util/downloader/downloader.go [hunk 14]
```diff
@@ -182,83 +183,68 @@ func (d *Downloader) downloadFile(ctx context.Context, out *os.File, stats *Stat
...
+				w, err := out.WriteAt(buf[written:n], offset+int64(written))
+				if err != nil {
+					d.mu.Unlock()
 
-func (d *Downloader) updateHasherWithExistingData(downloaded int64, hasher io.Writer) error {
-	if downloaded > 0 {
-		existingFile, err := os.Open(d.filePath)
-		if err != nil {
-			return ErrOpenFileExists
+					return ErrFileWriting
```
Comment (b00f) [inline util/downloader/downloader.go:201]: Better we return the `err` as it may have some useful information. You can forma error message.

File: util/downloader/downloader.go [hunk 15]
```diff
@@ -182,83 +183,68 @@ func (d *Downloader) downloadFile(ctx context.Context, out *os.File, stats *Stat
...
+			offset += int64(n)
+			d.downloaded += int64(n)
+			d.updateStats(d.downloaded, totalSize)
+			d.mu.Unlock()
 		}
-		defer func() {
-			_ = existingFile.Close()
-		}()
+		if err != nil {
+			if errors.Is(err, io.EOF) {
```
Comment (b00f) [inline util/downloader/downloader.go:211]: Why? Please add comment here

File: util/downloader/downloader.go [hunk 16]
```diff
@@ -182,83 +183,68 @@ func (d *Downloader) downloadFile(ctx context.Context, out *os.File, stats *Stat
...
-			}
-			if err != nil {
-				if err == io.EOF {
-					return d.finalizeDownload(hasher, stats)
-				}
+func (d *Downloader) finalizeDownload(stats *Stats) error {
+	// Recalculate the hash by re-reading the entire file
+	out, err := os.Open(d.filePath)
+	if err != nil {
+		return ErrOpenFileExists
```
Comment (b00f) [inline util/downloader/downloader.go:235]: You can either:

- Wrap `err` in `OpenFileError`
- Return `fmt.Errorf("...", err)`

File: util/downloader/downloader.go [hunk 17]
```diff
@@ -182,83 +183,68 @@ func (d *Downloader) downloadFile(ctx context.Context, out *os.File, stats *Stat
...
+	defer func() {
+		_ = out.Close()
+	}()
 
-				return fmt.Errorf("error reading response body: %w", err)
-			}
-		}
+	hasher := sha256.New()
+	if _, err := io.Copy(hasher, out); err != nil {
+		return ErrFileWriting
```
Comment (b00f) [inline util/downloader/downloader.go:243]: Same here.

**Review by b00f — CHANGES_REQUESTED** [review]

File: util/downloader/downloader.go [hunk 18]
```diff
@@ -6,24 +6,16 @@ import (
...
-	ErrSHA256Mismatch     = errors.New("sha256 mismatch")
-	ErrCreateDir          = errors.New("create dir error")
-	ErrInvalidFilePath    = errors.New("file path is a directory, not a file")
-	ErrGetFileInfo        = errors.New("get file info error")
-	ErrCopyExistsFileData = errors.New("error copying existing file data")
-	ErrDoRequest          = errors.New("error doing request")
-	ErrFileWriting        = errors.New("error writing file")
-	ErrNewRequest         = errors.New("error creating request")
-	ErrOpenFileExists     = errors.New("error opening existing file")
+const (
```
Comment (b00f) [inline util/downloader/downloader.go:16]: Make it `var`, then we can test it better (I think)

File: util/downloader/downloader.go (hunk 13 above)
Comment (Ja7ad) [reply util/downloader/downloader.go:123]: @b00f don't wait here return error for handling then send `wg.Done()` signal.

image

File: util/downloader/chunk_test.go (hunk 4 above)
Comment (Ja7ad) [reply util/downloader/chunk_test.go:16]: We can't test random we need known start and end range to check actual and excepted chunk list.

File: util/downloader/errors.go [hunk 19]
```diff
@@ -0,0 +1,18 @@
...
+	"fmt"
+)
+
+type Error struct {
+	Message string
+	Reason  error
+}
+
+func (e *Error) Error() string {
+	return fmt.Sprintf("%s: %s", e.Message, e.Reason.Error())
```
Comment (b00f) [inline util/downloader/errors.go:13]: Why don't simply use `fmt.Errorf(...)`

**Review by b00f — APPROVED** [review]
