### PR TITLE
fix: swagger doesn't work with multiple proto files

### LINKED ISSUE #378: Swagger doesn't work with multiple proto files
## Description

After splitting proto files, swagger doesn't work and user should enter proto files manually to check the APIs.

### How To Reproduce

Compile the latest code and check swagger.

### What Happened

This error shows: `Failed to load API definition.`

### Workaround

Changing proto file in Swagger and then click "Explore".

### PR DESCRIPTION
**Pull request by Ja7ad**
Fixed #378

### CODE REVIEW

**Review by b00f — APPROVED** [review]

File: www/grpc/swagger-ui/swagger-initializer.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ window.onload = function() {
 
   // the following lines will be replaced by docker/configurator, when it runs in a docker-container
   window.ui = SwaggerUIBundle({
-    url: "blockchain.swagger.json",
+    url: "apidocs.swagger.json",
```
Comment (b00f) [inline www/grpc/swagger-ui/swagger-initializer.js:6]: How about to rename it: `pactus.swagger.json`?

**Comment by Ja7ad** [comment]
@b00f Done

**Review by b00f — APPROVED** [review]
